import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/ui/footer";
import { NavbarDemo } from "@/components/ui/navbar";
import { Header } from "@/components/ui/header-section";
import { WorldMapDemo } from "@/components/ui/world-connectivity";
import { CardDemo } from "@/components/ui/animate-card";
import {ClerkProvider} from '@clerk/nextjs'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Modern Traveling Agency Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavbarDemo></NavbarDemo>
        
        {children}
        <Header></Header>
        <WorldMapDemo></WorldMapDemo>
        {/*  */}
        <CardDemo></CardDemo>
        <Footer></Footer>
      </body>
    </html>
    </ClerkProvider>
  );
}
